library(shiny)
library(shinydashboard)
library(ggplot2)
library(RColorBrewer)
#library(Cairo)
library(tidyverse)
library(data.table)
library(stringr)
library(vegan)
library(dplyr)
library(magrittr)
library(lubridate)
library(ape)
library(tidyr)
library(scales)
library(plotly)
library(rdrop2)
library(cowplot)

#options(repos = BiocManager::repositories())

#dashboard files
source("sourcefiles/sidebar.R")
source("sourcefiles/header.R")
source("sourcefiles/body.R")
source("sourcefiles/functions.R")

#ampvis2 functions
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_load.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_subset_samples.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_subset_taxa.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_rename.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.4.0/R/amp_heatmap.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/7b4842e301289a927b3ce19d399ba6e61ca5af0b/R/amp_ordinate.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_boxplot.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_function.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_timeseries.R")

dashboardPage(header, sidebar, body, title = "MiDAS dashboard")