library(shiny)
library(shinydashboard)
library(ggplot2)
library(RColorBrewer)
#library(Cairo)
library(tidyverse)
library(data.table)
library(stringr)
library(vegan)
library(dplyr)
library(magrittr)
library(lubridate)
library(ape)
library(tidyr)
library(scales)
library(plotly)
library(rdrop2)
library(cowplot)
library(openxlsx)
library(DT)

#options(repos = BiocManager::repositories())

#dashboard files
source("sidebar.R")
source("header.R")
source("body.R")
source("functions.R")

#ampvis2 functions
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_load.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_subset_samples.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_subset_taxa.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/2.2.8/R/amp_rename.R")
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/663c81e619713e3f85e4b5f7a8174f95174e5824/R/amp_heatmap.R") # the one with textmap + plot_functions=FALSE bug fixed
devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/7b4842e301289a927b3ce19d399ba6e61ca5af0b/R/amp_ordinate.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_boxplot.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_function.R")
#devtools::source_url("https://raw.githubusercontent.com/MadsAlbertsen/ampvis2/master/R/amp_timeseries.R")

dashboardPage(header, sidebar, body, title = "MiDAS dashboard")